---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.13
    environment:
      GOPROXY: https://athens.chuhlomin.com
    commands:
      - make lint test run
    when:
      event:
        - push
      branch:
        - main

trigger:
  branch:
    - main
